//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uAccount
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string userName { get; set; }
        public string pass { get; set; }
        public string role { get; set; }
    }
}
