//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteBusver2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stop
    {
        public Stop()
        {
            this.Times = new HashSet<Time>();
        }
    
        public int StopID { get; set; }
        public string StopName { get; set; }
        public string Street { get; set; }
        public string Long { get; set; }
        public string LAt { get; set; }
        public string MapsUsable { get; set; }
    
        public virtual ICollection<Time> Times { get; set; }
    }
}
