//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteBusver2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time
    {
        public int TimeID { get; set; }
        public System.TimeSpan Time1 { get; set; }
        public int StopID { get; set; }
        public int BusID { get; set; }
    
        public virtual Stop Stop { get; set; }
        public virtual Trasport Trasport { get; set; }
    }
}
