//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteBusver2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trasport
    {
        public Trasport()
        {
            this.Times = new HashSet<Time>();
        }
    
        public int BusID { get; set; }
        public string BusName { get; set; }
        public int Line { get; set; }
    
        public virtual ICollection<Time> Times { get; set; }
    }
}
