//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteBusver2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RouteBusDataBaseCRUDEntities : DbContext
    {
        public RouteBusDataBaseCRUDEntities()
            : base("name=RouteBusDataBaseCRUDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Stop> Stops { get; set; }
        public virtual DbSet<Time> Times { get; set; }
        public virtual DbSet<Trasport> Trasports { get; set; }
    }
}
